Added listing of all the commands.
CakeAndBanana/CakeBot pull request #48
Opened 2019-08-17 18:16 UTC by Kaynn-Cahya

Based on #3 

`help` just simply lists out all the commands in an embed.<br>The user can navigate through the different pages using the LeftArrow and RightArrow emoji.

*Alternatively*, the user can also filter the search by `help (filterHere)`.<br>In-code, it just uses `string.Contains` on the `Summary`, `Remarks` and `Name` attribute if applicable.

Pages are separated based on modules rather than length.

>The bot will just say a warning if the filter failed to find any respective commands.
The bot will not show the respective emojis if the commands can fit into a page.

### Code Design
**For handling Message Reactions**

`CommandHandler` makes the respective static `MessageReactionHandler` function subscribe to the respective `Client` object reaction event-handlers.

To make an object have a callback when a reaction-related event occurs to a message, let it implement `IMessageReactionHandle` and call `AddMessageReactionHandle` from `MessageReactionHandler`, with the input being the respective object.

Just remember to call `RemoveMessageReactionHandle` after you are done, with the input being the respective object.

2019-08-17 18:52 UTC, Darius-Wattimena requested changes

2019-08-17 18:52 UTC, Darius-Wattimena commented on Cake.Core/Discord/Modules/HelpModule/HelpModule.cs
Here might be a better place to do a check if the count != 1

This way you can remove the else if you have right now

2019-08-17 18:52 UTC, Darius-Wattimena commented on Cake.Core/Discord/Handlers/CommandHandler.cs
> +                if (context.Message.HasCharPrefix(Convert.ToChar(">"/*guild.Prefix*/), ref argPos))
Set back stuff like how it was first

2019-08-18 01:12 UTC, Kaynn-Cahya commented
> Here might be a better place to do a check if the count != 1
> 
>This way you can remove the else if you have right now

👍

2019-08-28 22:24 UTC, CakeAndBanana commented
Hello, Sorry for the late response (we were on vacation in Germany).

I was testing out the helpbook function and if you go from last page to next page, it goes to the second last page. Also can you add page numbers at the bottom as a footer.

2019-08-29 01:49 UTC, Kaynn-Cahya commented
@CakeAndBanana  👍 
Hopefully I did not misinterpret your meaning of `add a spacer before the description text of the command?`

2019-08-29 10:39 UTC, CakeAndBanana commented
Uhm, The page number is going backwards. When I'm going forward in the pages it goes from 3 to 2 and when I'm going backwards it's going from 2 to 3. Ignore the spacer part, I can't explain it well enough 😄

2019-08-29 11:20 UTC, Kaynn-Cahya commented
@CakeAndBanana 

> Uhm, The page number is going backwards. When I'm going forward in the pages it goes from 3 to 2 and when I'm going backwards it's going from 2 to 3.

Fixed it; 
P.S, I was thinking about books that flipped Left-to-Right 😅

2019-09-02 14:15 UTC, CakeAndBanana commented
Thanks for this PR, Everything looks fine.
I will push this to master :)

2019-09-02 14:15 UTC, merged