Try improved status embed formatting
CakeAndBanana/CakeBot pull request #51
Opened 2019-09-05 14:45 UTC by Kaynn-Cahya

Based on #47 

Currently, [Imgur](https://i.imgur.com/Q6dG5r8.png) is the new style.<Br>(Posted it on to the discord server too, by the way.)

Made each respective section of the status on to each embed field.

The footer now contains the up-time, it shows in this format:<br>`x Years; x Months; x Days; x Hours; x Minutes;`
It will not show any of the respective time if the value is `0` for that time.

2019-09-06 10:22 UTC, CakeAndBanana requested changes
Maybe not use semi columns for the spacing between the time, use , or ○ between it.
The guild shards and total shards can be combined.

2019-09-06 10:22 UTC, CakeAndBanana commented on Cake.Core/Discord/Embeds/CakeModuleEmbeds.cs
> +                    new EmbedFieldBuilder().WithName("Guild Shard")
Combine Guild shard and Shards to 1 field, Like this: "(guildShard)/(totalShards)". No need to seperate them.

2019-09-06 14:23 UTC, Kaynn-Cahya commented
@CakeAndBanana 👍 
This is now the new format after the update: https://i.imgur.com/NokjsZg.png

It seperates the times by `,` rather than semi-colons.

2019-09-10 15:51 UTC, CakeAndBanana commented
I think this looks fine enough, I will push this to master :).
Thanks for the PR!

2019-09-10 15:52 UTC, merged